import { getThemeBehaviour } from './themes.js';

export const LEVELS = [
  {
    key: 'L1',
    name: 'Debris Drift',
    duration: 90,
    theme: 'synth-horizon',
    themeBehaviour: getThemeBehaviour('synth-horizon'),
    overlays: { tint: 'rgba(0,0,0,0.0)' },
    starfield: {
      density: 0.9,
      twinkle: { amplitude: 0.18, speed: 0.95 },
      sizeRange: [1.2, 2.2],
    },
    enemyWeights: { asteroid: 1.0, strafer: 0.8, drone: 0.4, turret: 0.4 },
    waves: [
      { at: 3.0, type: 'asteroid', count: 6, params: { vy: [60, 120] } },
      { at: 8.5, type: 'strafer', count: 2, params: { fireCd: [1200, 1800] } },
      { at: 20.0, type: 'drone', count: 1, params: { steerAccel: 28 } },
    ],
    boss: {
      midBoss: {
        kind: 'intruder-scout',
        hp: 220,
        triggerRatio: 0.6,
        introMessage: 'INTRUDER ALERT',
        introColour: '#ff6a6e',
        bannerColour: '#ffefef',
      },
      finalBoss: { kind: 'overlord', hp: 360, phases: [0.7, 0.4] },
    },
    mutators: { windX: 0, squalls: false },
  },
  {
    key: 'L2',
    name: 'Ion Squalls',
    duration: 105,
    theme: 'luminous-depths',
    themeBehaviour: getThemeBehaviour('luminous-depths'),
    overlays: { tint: 'rgba(80,0,120,0.06)' },
    starfield: {
      density: 1.35,
      twinkle: { amplitude: 0.32, speed: 1.6 },
      sizeRange: [0.9, 1.6],
    },
    enemyWeights: { asteroid: 0.6, strafer: 0.5, drone: 1.1, turret: 0.3 },
    waves: [
      { at: 4.0, type: 'drone', count: 2, params: { steerAccel: 32 } },
      { at: 12.0, type: 'asteroid', count: 5, params: { vy: [70, 120] } },
      { at: 24.0, type: 'strafer', count: 1, params: { fireCd: [1200, 1600] } },
    ],
    boss: {
      midBoss: {
        kind: 'intruder-vigil',
        hp: 260,
        triggerRatio: 0.6,
        introMessage: 'INTRUDER ALERT',
        introColour: '#ff668f',
        bannerColour: '#ffe5f2',
      },
      finalBoss: { kind: 'warden', hp: 440, phases: [0.8, 0.5] },
    },
    mutators: { windX: 25, squalls: true },
  },
  {
    key: 'L3',
    name: 'Ember Breaker',
    duration: 110,
    theme: 'ember-overdrive',
    themeBehaviour: getThemeBehaviour('ember-overdrive'),
    overlays: { tint: 'rgba(120,40,0,0.08)' },
    starfield: {
      density: 1.1,
      twinkle: { amplitude: 0.28, speed: 1.35 },
      sizeRange: [1.1, 2.1],
    },
    enemyWeights: { asteroid: 0.8, strafer: 1.1, drone: 0.9, turret: 0.6 },
    waves: [
      { at: 3.5, type: 'asteroid', count: 5, params: { vy: [90, 150] } },
      { at: 9.0, type: 'strafer', count: 2, params: { fireCd: [900, 1400] } },
      { at: 16.0, type: 'turret', count: 1, params: { bulletSpeed: 260 } },
      { at: 28.0, type: 'strafer', count: 3, params: { speedMin: 150, speedMax: 220 } },
    ],
    boss: {
      midBoss: {
        kind: 'intruder-blaze',
        hp: 300,
        triggerRatio: 0.6,
        introMessage: 'INTRUDER ALERT',
        introColour: '#ff7354',
        bannerColour: '#ffe4d8',
      },
      finalBoss: { kind: 'overdrive', hp: 520, phases: [0.75, 0.45] },
    },
    mutators: { windX: -18, squalls: false },
  },
  {
    key: 'L4',
    name: 'Cosmic Abyssal Drift',
    duration: 125,
    theme: 'cosmic-abyss',
    themeBehaviour: getThemeBehaviour('cosmic-abyss'),
    overlays: { tint: 'rgba(20, 40, 90, 0.08)' },
    starfield: {
      density: 1.45,
      twinkle: { amplitude: 0.34, speed: 1.25 },
      sizeRange: [1.1, 2.6],
    },
    enemyWeights: {
      asteroid: 0.7,
      strafer: 0.9,
      drone: 0.85,
      turret: 1.05,
      splitter: 1.1,
      'shield-drone': 0.95,
    },
    waves: [
      { at: 5.5, type: 'splitter', count: 1, params: { hp: 5, accel: 48, childRange: [2, 3] } },
      { at: 12.0, type: 'drone', count: 3, params: { steerAccel: 36 } },
      { at: 18.0, type: 'shield-drone', count: 1, params: { cooldown: 3600, duration: 3200, range: 200 } },
      { at: 26.0, type: 'splitter', count: 2, params: { hp: 6, accel: 50, miniAccel: 140 } },
      { at: 34.0, type: 'turret', count: 2, params: { fireCd: [900, 1300], bulletSpeed: 240 } },
      { at: 44.0, type: 'shield-drone', count: 1, params: { cooldown: 3400, targets: 2, range: 210 } },
    ],
    boss: {
      midBoss: {
        kind: 'intruder-veil',
        hp: 340,
        triggerRatio: 0.6,
        introMessage: 'NEBULA ANOMALY',
        introColour: '#3df2ff',
        bannerColour: '#dcefff',
      },
      finalBoss: { kind: 'abyssal-core', hp: 620, phases: [0.72, 0.46] },
    },
    mutators: { windX: 8, squalls: true },
  },
];
